version: '3'
services:
  timemachine:
    container_name: timemachine
    image: "mbentley/timemachine:smb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - timemachine-var-lib-samba:/var/lib/samba
      - timemachine-var-cache-samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
      - /mnt/timemachine:/opt/timemachine
    restart: always
    network_mode: host